/*
Weapon : Weapon Mastery associations Mastery Properties are provided in the 2024 free rules on D&D Beyond: https://www.dndbeyond.com/sources/dnd/free-rules/equipment#Weapons
*/
export const weaponMasteries = [
  { id: 'staff', baseItem: 'quarterstaff', mastery: 'topple' },
  { id: 'wooden-staff', baseItem: 'quarterstaff', mastery: 'topple' },
  { id: 'battleaxe', baseItem: 'battleaxe', mastery: 'topple' },
  { id: 'blowgun', baseItem: 'blowgun', mastery: 'vex' },
  { id: 'club', baseItem: 'club', mastery: 'slow' },
  { id: 'dagger', baseItem: 'dagger', mastery: 'nick' },
  { id: 'dart', baseItem: 'dart', mastery: 'vex' },
  { id: 'flail', baseItem: 'flail', mastery: 'sap' },
  { id: 'glaive', baseItem: 'glaive', mastery: 'graze' },
  { id: 'greataxe', baseItem: 'greataxe', mastery: 'cleave' },
  { id: 'greatclub', baseItem: 'greatclub', mastery: 'push' },
  { id: 'greatsword', baseItem: 'greatsword', mastery: 'graze' },
  { id: 'halberd', baseItem: 'halberd', mastery: 'cleave' },
  { id: 'hand-crossbow', baseItem: 'handcrossbow', mastery: 'vex' },
  { id: 'handaxe', baseItem: 'handaxe', mastery: 'vex' },
  { id: 'heavy-crossbow', baseItem: 'heavycrossbow', mastery: 'push' },
  { id: 'javelin', baseItem: 'javelin', mastery: 'slow' },
  { id: 'lance', baseItem: 'lance', mastery: 'topple' },
  { id: 'light-crossbow', baseItem: 'lightcrossbow', mastery: 'slow' },
  { id: 'light-hammer', baseItem: 'lighthammer', mastery: 'nick' },
  { id: 'longbow', baseItem: 'longbow', mastery: 'slow' },
  { id: 'longsword', baseItem: 'longsword', mastery: 'sap' },
  { id: 'mace', baseItem: 'mace', mastery: 'sap' },
  { id: 'maul', baseItem: 'maul', mastery: 'topple' },
  { id: 'morningstar', baseItem: 'morningstar', mastery: 'sap' },
  { id: 'musket', baseItem: 'musket', mastery: 'slow' },
  { id: 'pike', baseItem: 'pike', mastery: 'push' },
  { id: 'pistol', baseItem: 'pistol', mastery: 'vex' },
  { id: 'quarterstaff', baseItem: 'quarterstaff', mastery: 'topple' },
  { id: 'rapier', baseItem: 'rapier', mastery: 'vex' },
  { id: 'scimitar', baseItem: 'scimitar', mastery: 'nick' },
  { id: 'shortbow', baseItem: 'shortbow', mastery: 'vex' },
  { id: 'shortsword', baseItem: 'shortsword', mastery: 'vex' },
  { id: 'sickle', baseItem: 'sickle', mastery: 'nick' },
  { id: 'sling', baseItem: 'sling', mastery: 'slow' },
  { id: 'spear', baseItem: 'spear', mastery: 'sap' },
  { id: 'trident', baseItem: 'trident', mastery: 'topple' },
  { id: 'war-pick', baseItem: 'warpick', mastery: 'sap' },
  { id: 'warhammer', baseItem: 'warhammer', mastery: 'push' },
  { id: 'whip', baseItem: 'whip', mastery: 'slow' }
];